name: Trigger Cron Job Worker

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: data-update
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.db README.md
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: run weekly data fetch job"
            git push
          fi
